import Head from "next/head";
import { EventCategory } from "@/src/types/event-category";
import Home from "@/src/components/home/home";

export async function getServerSideProps() {
	const { events_categories } = await import("data/data.json");

	return {
		props: {
			data: events_categories,
		},
	};
}

interface HomePageProps {
	data: EventCategory[];
}

function HomePage({ data }: HomePageProps) {
	return (
		<>
			<Head>
				<title>Events App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Home data={data} />
		</>
	);
}

export default HomePage;
